---
version: "3.7"
services:
  api-generator-go:
    build:
      context: .
      dockerfile: api-generator.Dockerfile
    command: generate -i /mnt/api/api.json -g go -o /mnt/dynamicbeat/types -c /mnt/api/go.yml -Dmodels --enable-post-process-file
    environment:
      GO_POST_PROCESS_FILE: /usr/bin/gofmt -w
    image: api-generator:latest
    volumes:
      - "../:/mnt"
    user: 1000:1000

  api-generator-typescript:
    command: generate -i /mnt/api/api.json -g typescript-axios -o /mnt/kibana-plugin/common -c /mnt/api/typescript-axios.yml -t /mnt/api/templates/typescript-axios --api-package scorestack-api --model-package checks
    image: openapitools/openapi-generator-cli:v4.3.1
    volumes:
      - "../:/mnt"
    user: 1000:1000

  dynamicbeat-ci:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: ci
    environment:
      GOPATH: /home/scorestack/go
    image: dynamicbeat-ci:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "./scripts/dynamicbeat:/scripts"
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: scorestack

  dynamicbeat-devcontainer:
    build:
      context: .
      dockerfile: dynamicbeat.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      GOPATH: /home/scorestack/go
    image: dynamicbeat-devcontainer:latest
    volumes:
      - "../:/home/scorestack/go/src/github.com/s-newman/scorestack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    user: scorestack

  elasticsearch:
    environment:
      - discovery.type=single-node
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    ports:
      - 9200:9200

  kibana-plugin-ci:
    build:
      context: .
      dockerfile: kibana-plugin.Dockerfile
      target: ci
    image: neonspandex/kibana-dev:7.7.1
    volumes:
      - "../kibana-plugin:/home/node/kibana/plugins/scorestack"
      - "./scripts/kibana-plugin:/scripts"
    user: node

  kibana-plugin-devcontainer:
    build:
      context: .
      dockerfile: kibana-plugin.Dockerfile
      target: devcontainer
    command: /bin/sh -c "while sleep 1000; do :; done"
    image: kibana-plugin-devcontainer:latest
    ports:
      - 5601:5601
    volumes:
      - "../:/home/node/kibana/plugins"
    user: node
