---
name: Dynamicbeat

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: sudo chown -R 1000:1000 .
      - name: Generate check types
        run: docker-compose -f dockerfiles/docker-compose.yml up api-generator-go
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-ci
      - name: Lint dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml run dynamicbeat-ci /scripts/lint.sh

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fix file permissions
        run: sudo chown -R 1000:1000 .
      - name: Generate check types
        run: docker-compose -f dockerfiles/docker-compose.yml up api-generator-go
      - name: Set up container
        run: docker-compose -f dockerfiles/docker-compose.yml build dynamicbeat-ci
      - name: Test dynamicbeat
        run: docker-compose -f dockerfiles/docker-compose.yml run dynamicbeat-ci /scripts/test.sh
